# Generated by Django 4.0.1 on 2022-02-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
