# Generated by Django 4.0.1 on 2022-02-13 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_thread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
