# Generated by Django 4.0.1 on 2022-02-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_thread_alter_message_receiver_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
    ]
