# Generated by Django 4.0.1 on 2022-02-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
    ]
